name = "lukairo-engine"
type = "javascript"
account_id = "5d666172fd0919ec532f6ebcd85cbd3d"
workers_dev = true
main = "src/index.ts"
compatibility_date = "2026-01-07"

[env.production]
zone_id = "1fa0177eaf2e2feb41ce7dea73c7924e"
routes = [
	{ pattern = "lukairoengine.ca/*", zone_id = "1fa0177eaf2e2feb41ce7dea73c7924e" }
]
