name = "lukairo-engine"
main = "./app.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

# Serve static assets from cf-pages directory
[site]
bucket = "./cf-pages"

[vars]
VALUE_FROM_CLOUDFLARE = "lukairo-edge"
