name = "lukairo-engine"
main = "./workers/app.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

workers_dev = true

# Assets
assets = { directory = "./build/client/" }

[vars]
VALUE_FROM_CLOUDFLARE = "lukairo-edge"
