name = "lukairo-engine"
main = "workers/app.ts"
compatibility_date = "2025-01-01"
workers_dev = true

[vars]
VALUE_FROM_CLOUDFLARE = "lukairo-edge"

[[d1_databases]]
binding = "DB"
database_name = "lukairo-db"
database_id = "YOUR_DATABASE_ID"
